In [ ]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
#creating 1D array and checking it's type and shape
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
arr.shape


[1 2 3 4 5]
<class 'numpy.ndarray'>


(5,)

In [ ]:
#creating 2D array and checking its shape
arr1 = np.array([[1,2,3.3],[4,5,6.6]])
print(arr1)
arr1.shape

[[1.  2.  3.3]
 [4.  5.  6.6]]


(2, 3)

In [ ]:
#creating 3D array and checking its shape
arr2 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                 [[10,11,12],[13,14,15],[16,17,18]]])
print(arr2)
arr2.shape

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


(2, 3, 3)

In [ ]:
#reshaping 1D array and checking its shape
reshaped = arr.reshape((1,5))
print(reshaped)
reshaped.shape
reshaped[0][2]  #accessing elemnets through index

[[1 2 3 4 5]]


3

In [ ]:
#checking no. of elements in array
arr.size, arr1.size, arr2.size

(5, 6, 18)

In [ ]:
#checking no. of dimensions in array
arr.ndim, arr1.ndim, arr2.ndim

(1, 2, 3)

In [ ]:
#chceking datatype of array
arr.dtype, arr1.dtype, arr2.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [ ]:
#creating identity matrix --> all elements are 1 (float)
i = np.ones((3,3))
print(i)

#creating identity matrix --> all elements are 1 (int)
j = np.ones((3,3),dtype=int)
print(j)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# storing array as row major order
j = np.ones((3,4),dtype=int,order='C')
print(j)

# storing array as column major order
j = np.ones((3,4),dtype=int,order='F')
print(j)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
#using random method to generate random values for array (between 0 - 1)
randomArray = np.random.random((3,4))
print(randomArray)

#using randint method to generate integer values for array
randomArray2 = np.random.randint(0,10,size=(3,4))
print(randomArray2)

[[0.20483948 0.0167136  0.72555907 0.5682083 ]
 [0.80898329 0.11645869 0.13107579 0.40127811]
 [0.71220888 0.6569299  0.61019194 0.99328558]]
[[0 7 4 5]
 [2 4 1 1]
 [2 8 0 0]]


In [ ]:
#using arange method to generate 1D array in a range with step
rangeArray = np.arange(0,10,3)
print(rangeArray)

[0 3 6 9]


In [ ]:
#unique method returns the unique elements of array in ascending order
arr3 = np.array([1,2,3,4,2,3,5,6,3,2])
np.unique(arr3)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#creating a dataframe from numpy array

import pandas as pd
df = pd.DataFrame(arr1)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.6